name: Publish AspNet to NuGet

on:
  workflow_dispatch:
    inputs:
      version:
        description: "AspNet package version"
        required: true

jobs:
  publish-aspnet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: dotnet restore
      - run: dotnet build --configuration Release
      - run: dotnet test --configuration Release

      - name: Pack AspNet
        run: |
          dotnet pack src/FeatureFlags.Lite.AspNet \
            -c Release \
            -p:PackageVersion=${{ github.event.inputs.version }} \
            -o ./nupkg

      - name: Publish AspNet
        run: |
          dotnet nuget push ./nupkg/*.nupkg \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json